# iOS signing: use Codemagic UI (Integrations + Code signing identities).
# Do NOT use fetch-signing-files --create in a script; that causes
# "Cannot save Signing Certificates without certificate private key".
# Instead: add API key in Integrations, then Create certificate in Code signing identities.
# See IOS_CODEMAGIC_SIGNING.md for step-by-step setup.
workflows:
  ios_testflight:
    name: iOS - Build & Upload to TestFlight (no local Mac)
    max_build_duration: 60
    integrations:
      app_store_connect: ClearDish AppStore
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hitratech.cleardish
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: ereen
          include: true
          source: true
    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
